version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount the entire project directory for hot reload
      - .:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
      # Exclude .next to avoid conflicts
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true